In [2]:
# numpy 调整数组的形状
import numpy as np

a = np.random.randint(1, 100, size = (5,6)) #生成1~ 100的数，5行6列

a


array([[67, 25, 73, 28, 98, 94],
       [20, 13, 84, 16, 78, 74],
       [98, 11,  8, 65,  2, 75],
       [62, 63, 33, 74, 36, 87],
       [ 9, 34, 27, 44, 10, 25]])

In [4]:
# 将所有的值都转为一维的,不改变原numpy的值
a.ravel()

array([67, 25, 73, 28, 98, 94, 20, 13, 84, 16, 78, 74, 98, 11,  8, 65,  2,
       75, 62, 63, 33, 74, 36, 87,  9, 34, 27, 44, 10, 25])

In [5]:
a.reshape(10,3) # 调节为需要的大小

array([[67, 25, 73],
       [28, 98, 94],
       [20, 13, 84],
       [16, 78, 74],
       [98, 11,  8],
       [65,  2, 75],
       [62, 63, 33],
       [74, 36, 87],
       [ 9, 34, 27],
       [44, 10, 25]])

In [6]:
a.T #a转置

array([[67, 20, 98, 62,  9],
       [25, 13, 11, 63, 34],
       [73, 84,  8, 33, 27],
       [28, 16, 65, 74, 44],
       [98, 78,  2, 36, 10],
       [94, 74, 75, 87, 25]])

In [8]:
a.flatten() #类似于ravel,转为一维

array([67, 25, 73, 28, 98, 94, 20, 13, 84, 16, 78, 74, 98, 11,  8, 65,  2,
       75, 62, 63, 33, 74, 36, 87,  9, 34, 27, 44, 10, 25])

### 如果shape变换中一个维度为 -1，则这个维度包含的元素将被直接计算

In [10]:
a.reshape(10,-1) # 知道设置10行不知道设置多少列，则在不知道的维度记-1

array([[67, 25, 73],
       [28, 98, 94],
       [20, 13, 84],
       [16, 78, 74],
       [98, 11,  8],
       [65,  2, 75],
       [62, 63, 33],
       [74, 36, 87],
       [ 9, 34, 27],
       [44, 10, 25]])

### numpy 随机数的产生 （测试，业务需求，权重的初始化）

In [11]:
np.random.rand(10)

array([ 0.8041245 ,  0.83491409,  0.54275155,  0.5959575 ,  0.29550877,
        0.68806224,  0.73882757,  0.31805257,  0.53760798,  0.67928864])

In [13]:
np.random.rand(3,4)

array([[ 0.08147694,  0.78160679,  0.76940869,  0.33471293],
       [ 0.39209761,  0.16230261,  0.84947273,  0.09588585],
       [ 0.53324794,  0.92187451,  0.87679823,  0.589191  ]])

In [15]:
np.random.randn(10) # 产生符合正态分布的随机数

array([-0.29215335,  2.55640814, -1.48315306,  0.12083674, -0.9831212 ,
        0.7753259 , -1.56668109, -1.0395112 ,  0.89765688, -0.68849489])

In [19]:
np.random.randint(100) # 产生不大于100的整数随机数

50

In [20]:
np.random.randint(1,100, size = (2,50)) # 起始位，终止位

array([[24, 19, 43, 92, 36, 91, 42, 14, 44, 58, 70, 50, 41, 35, 13, 27, 48,
        67, 79, 11, 73, 94, 38, 60, 82, 19, 63, 87, 94, 58, 64, 59, 94, 33,
        17, 92, 37, 82, 96, 96, 49, 39, 76, 13, 39, 52, 27, 76, 58, 89],
       [ 6, 16, 13, 51, 18, 39,  1, 76, 46, 83, 83, 76,  6, 92, 21, 62, 47,
        33, 47, 69, 14, 69, 95, 34, 48, 65, 22,  9, 94, 70,  9, 83, 41, 18,
        63, 81, 10, 23, 57, 76, 11, 85,  9, 85, 71, 41, 78, 44, 20,  7]])

In [23]:
np.random.random((3,3)) # 产生0~1之间的浮点数

array([[ 0.60750879,  0.31158005,  0.20416022],
       [ 0.48423033,  0.77528548,  0.25953597],
       [ 0.36783855,  0.34730919,  0.56355659]])

In [25]:
np.random.choice(10,(3,8)) # 抽取0~10之间的数，抽取3*8=24个，按3*8排列

array([[2, 8, 6, 5, 4, 7, 2, 8],
       [1, 3, 4, 8, 4, 8, 5, 5],
       [3, 4, 7, 0, 4, 6, 5, 6]])

In [28]:
np.random.choice(10,(3,8)).size

24

In [29]:
# 直接填入值,然后指定形状大小
np.random.choice([2,8,7,4,6,5],(2,3))

array([[4, 6, 6],
       [4, 2, 6]])

## 数组的数学计算

In [31]:
import numpy as np

a = np.random.random([3,4])

b = np.random.random([3,4])

In [32]:
a

array([[ 0.49443484,  0.74221179,  0.22360126,  0.93582893],
       [ 0.86725139,  0.397984  ,  0.87611056,  0.86129712],
       [ 0.25640269,  0.58907551,  0.68430778,  0.30800841]])

In [33]:
b

array([[ 0.22653072,  0.0996063 ,  0.98788073,  0.03316501],
       [ 0.35851462,  0.971515  ,  0.28681143,  0.13792111],
       [ 0.71159804,  0.5217052 ,  0.49465996,  0.23265078]])

In [34]:
# 数组与数的加减乘除 是整个数组中的元素全部与该值进行加减乘除（广播）, 
# 每个元素除某个值，用于求平均

a + 10

array([[ 10.49443484,  10.74221179,  10.22360126,  10.93582893],
       [ 10.86725139,  10.397984  ,  10.87611056,  10.86129712],
       [ 10.25640269,  10.58907551,  10.68430778,  10.30800841]])

In [35]:
a * 10

array([[ 4.94434842,  7.4221179 ,  2.23601263,  9.35828929],
       [ 8.67251388,  3.97983996,  8.76110558,  8.61297117],
       [ 2.56402694,  5.89075506,  6.84307783,  3.08008415]])

In [ ]:
a + - * / b #数组大小相同

In [36]:
np.add(a, b)
np.subtract(a, b)
np.multiply(a, b)
np.divide(a, b)

array([[  2.18263927,   7.45145403,   0.22634439,  28.21736098],
       [  2.41901263,   0.40965296,   3.05465711,   6.24485329],
       [  0.36031956,   1.12913483,   1.38339028,   1.32390882]])

In [37]:
# 内积的求解（矩阵线性代数）

a.dot(b.T)
np.dot(a, b.T)

array([[ 0.4378618 ,  1.09153397,  1.06738253],
       [ 1.13015846,  1.0676393 ,  1.45852296],
       [ 0.80298829,  0.90296796,  0.89993746]])